### ISSUE TITLE
Sandy Beach "Man" Request digging

### ISSUE THREAD

**Issue by zenseii** [teamrocketslime/RS3DS-Releases#10]
### Description
"I'll give you Broadsword for diggin
g."

### Location of bug
Sandy Beach. Take te cannon to get to where the slime is.

![2019-08-07_01-59-15 765_bot](https://user-images.githubusercontent.com/12501091/62662607-e7ee2680-b974-11e9-8eeb-3ee8ffefac54.png)

### Excerpt or Screenshot
![2019-08-07_01-59-15 765_top](https://user-images.githubusercontent.com/12501091/62662615-ede40780-b974-11e9-81c8-4875a9e6b24c.png)

**Comment by lgnmcrules** [comment]
Fixed
