### ISSUE TITLE
Young Kid/Girl, Funadel's Islet/Isle, Ship customization, Shivarel, Gun valley Town Kid.

### ISSUE THREAD

**Issue by zenseii** [teamrocketslime/RS3DS-Releases#11]
### Description

- [x] Nr.1 Young Kid turns into Young Girl

- [x] Nr.2 In overworld it is called Funadel Isle, while list of places calls it Funadel's Islet

- [x] _Edit1:_ Nr.3 In Cid's ship customization, in lower screen, there are inconsistencies in the general naming of the ship parts:

- "Oars" is called "Decor" in the subsequent menu, and it regards "side" parts .
- "Figoore" is called "Bow" and regards "Head" parts.
- "Hull" is called "Hull" and regards "body" parts (not sure if this needs to be changed?).
- "Mast" is the same in all three instances.

- [x] **Nr.4** Shiveral is called Shivarel many places.
          

- [x] Ex.1 Snowy Shivarel.
- [x] The "L" is cut off as well.

- [x] Ex.2 Dialog with Hooly in Snow Country Harbor.
- [x] Ex.3 "Shivarel Harbor" bottom screen.
- [x] Shivarel Harbor is aligned too far up too.

- [x] Ex.4 Dialog with Gooshido in Icy Hideout 2.
- [x] Ex.5 Bottom screen when in Shiveral.

- [x] **Nr.5** Volcano Island is refered to as just volcano by Town Kid. 
- [x] There is also a text issue with "get" getting split . 
- [x] As for grammar the infinite article is missing before Cloaking Device.
I suggest writing either "[...]to get a Cloaking Device at the/a volcano." or "[...] at Volcano Island." The latter is probably too long. Also, I don't remember if it is Island or Isle.

- [x] **Nr.6** Bo talks about this being the final save spot AFTER you've beaten the final boss.

- [x] **Nr.7** Description of Demon Axe seems to be for another item.

### Location of inconsistency
Nr.1 Jungle Area.
Nr.2 "Baltic Sea" near Funadel.
Nr.3 Cid's ship customization.
Nr.4 Bottom Screen namesa and dialogs.
Nr.5 Church in Gun Valley.
Nr.6 During ending scenes after finshing final sea battle.
Nr.7 Item description of Demon Axe.

### Excerpt or Screenshot
Nr.1
![2019-08-07_01-29-58 253_top](https://user-images.githubusercontent.com/12501091/62664930-b75eba80-b97d-11e9-95e5-56e32e5daa52.png)
![2019-08-07_01-30-28 515_top](https://user-images.githubusercontent.com/12501091/62664931-b75eba80-b97d-11e9-86e2-ec51cd2b1d53.png)

Nr.2
![IMG_20190805_155730](https://user-images.githubusercontent.com/12501091/62665081-423fb500-b97e-11e9-80e1-c788761d6d60.jpg)
![IMG_20190805_155927](https://user-images.githubusercontent.com/12501091/62665082-423fb500-b97e-11e9-9595-3526b334af36.jpg)

Nr.3
![2019-08-07_02-12-47 988_bot](https://user-images.githubusercontent.com/12501091/62667046-4374e000-b986-11e9-81c3-fd5d43cdc446.png)
![2019-08-07_02-12-59 954_bot](https://user-images.githubusercontent.com/12501091/62667054-4d96de80-b986-11e9-960d-659e6be3a698.png)

Nr.4
Ex.1
![2019-08-30_22-49-07 190_bot](https://user-images.githubusercontent.com/12501091/64499359-f5bb0280-d2b8-11e9-945b-3612915ea3a4.png)
Ex.2
![2019-08-27_06-26-34 457_top](https://user-images.githubusercontent.com/12501091/64499377-08353c00-d2b9-11e9-90f1-e239a4fe573d.png)
![2019-08-27_06-26-34 457_bot](https://user-images.githubusercontent.com/12501091/64499378-08353c00-d2b9-11e9-8fc4-5803602141d7.png)
Ex.3
![2019-08-27_09-19-48 144_bot](https://user-images.githubusercontent.com/12501091/64499415-31ee6300-d2b9-11e9-8367-98a04bd59855.png)
Ex.4
![2019-08-30_22-39-00 686_top](https://user-images.githubusercontent.com/12501091/64499430-3fa3e880-d2b9-11e9-838a-e1b9466b55ba.png)
![2019-08-30_22-39-00 686_bot](https://user-images.githubusercontent.com/12501091/64499431-3fa3e880-d2b9-11e9-8d6c-75c6c37123ef.png)
Ex.5
![2019-08-27_09-21-58 528_bot](https://user-images.githubusercontent.com/12501091/64499445-492d5080-d2b9-11e9-855c-379107b8e66e.png)

Nr.5
![2019-09-04_14-11-06 667_top](https://user-images.githubusercontent.com/12501091/64499676-61ea3600-d2ba-11e9-8b72-9f048a5b95d8.png)
![2019-09-04_14-11-06 667_bot](https://user-images.githubusercontent.com/12501091/64499677-61ea3600-d2ba-11e9-98a4-dae5c2b6c84d.png)

Nr.6
![2019-09-08_18-09-50 394_top](https://user-images.githubusercontent.com/12501091/64500684-7a5c4f80-d2be-11e9-8a87-2808b538b11e.png)

Nr.7
![2019-09-07_00-45-56 650_top](https://user-images.githubusercontent.com/12501091/64500744-babbcd80-d2be-11e9-88d2-fcb207cb007f.png)

### Additional Info
Nr.1 Young Kid is referred to as Young Kid in the Request Log too.

**Comment by zenseii** [comment]
Added another inconsistency. Please tell me if it is necessary for me to comment when I edit the first post.

**Comment by CakeLancelot** [comment]
Not strictly necessary, but it is appreciated.

**Comment by lgnmcrules** [comment]
All fixed.
Regarding Nr.3, Oars and Decor were fixed.  Figoore was unchanged from Bow and Head due to part name differences.  Hull and Body are unchanged.

**Comment by zenseii** [comment]
I added several inconsistencies.

**Comment by lgnmcrules** [comment]
Fixed
