### ISSUE TITLE
Ship parts shop, requests, capitalization, cruelcumber, Roads Scholar etc.

### ISSUE THREAD

**Issue by zenseii** [teamrocketslime/RS3DS-Releases#13]
### Description

- [x] **Nr.1** In the ship parts shop, there are several capitalization, truncation and grammar errors, in both names of parts and their descriptions:

- [x] **Part names:**

- "mast" is sometimes with capital m and sometimes not. 
- Sometimes parts have names truncated with what part it is: "Hammerside", "Golemast", "Platmast"
- "Head" has always capital H, while other parts are mostly miniscule("side", "body"...).

- [x] **Part descriptions (Nr.1):**

- Platy Head *Star*:"Platyhead" should have lowercase p.
- Hammerside. "Hammer Side" should be "Hammer side".
- For all the Hammer parts the phrase: "A ship for the dream of sweets." might be better as "A ship for sweet dreams.", or omitting the "the" and making dream plural, giving "A ship for dreams of sweets." or other ways.
- "Golemast" should have "iron Golem" with either all capital "Iron Golem" or all miniscule "iron golem".
- Slimenian side is called "Slimenian Side" with capital S in side, should be miniscule.
- Sanguini side has capital S in side in description.
- Penguin side has capital S in side. Might be better to write the indefinite article before child "Penguin side with a child's bugle.".

- [x] **Nr.2** After clearing the ship battle challenge in "Brazil", "Cleared" has a capital C instead of lowercase.

- [x] **Nr.3** After getting zoom, Hooly's phrase can be written as: "It does seem pretty useful, but we can't forget about the map!" or "Does seem pretty useful... But we can't forget about the map!", instead of "Does seem pretty useful. But we can't forget about the map!"

- [x] **Nr.4** "Roads Scholar" in What the Town should maybe have his name changed to "Scholar Roads" since it seems like Scholar is his title, unless there is some hidden reference behind his name being like that, though I do not see it. (e.g. _"Trode's Color"_? He's green like King Trode...)

- [x] **Nr.5** Devil's Scythe description might be better as "Hits ships easily when fired at long-range!" rather than "Hits ship easily when fired long-range!". Although I'm not sure how you fire at long-range in the game, unless it means the artillery-ish cannon.

- [x] **Nr.6** Youngster in sandy beach says "searching eastward". "searching to the east." sound better.

- [x] **Nr.7** All requests in the request log are truncated with the number of the request. E.g. "Request1" instead of "Request 1".

- [x] **Nr.8** In request 20's description, "I wonder if you have dug at the dig point nearby here..." It is better if you drop "here" and move "nearby": "I wonder if you have dug at the nearby dig point...". Still, the running theme in What the Bay is a sort of broken English, so a complete rephrasal and making it sound worse might be better.

- [x] **Nr.9** In the description of Cruelcumber, the whole part in brackets should be moved to the next line.

### Location of bug
**Nr.1** Cid's ship part shop

**Nr.2** 
![2019-08-07_01-05-52 166_bot](https://user-images.githubusercontent.com/12501091/62670194-a3718380-b992-11e9-82e9-b939a98823bf.png)

**Nr.3** Outside What the Bay after you finish it.

**Nr.4**
![2019-08-07_01-24-47 724_bot](https://user-images.githubusercontent.com/12501091/62670369-49bd8900-b993-11e9-9401-60a2e554aaa3.png)

**Nr.5** In item description in pause menu

**Nr.6**
![2019-08-07_01-58-19 819_bot](https://user-images.githubusercontent.com/12501091/62670424-7e314500-b993-11e9-87b4-13d1077a7b20.png)

**Nr.7 & Nr. 8** Request log in pause menu.

**Nr.9** Monster description in pause menu.

### Excerpt or Screenshot
**Nr.1**
![2019-08-08_02-04-39 657_bot](https://user-images.githubusercontent.com/12501091/62670530-dc5e2800-b993-11e9-8050-7ed2f4afab61.png)
![2019-08-08_02-04-39 657_top](https://user-images.githubusercontent.com/12501091/62670549-e4b66300-b993-11e9-9c84-42c8d6f64e43.png)
![2019-08-07_01-12-04 203_bot](https://user-images.githubusercontent.com/12501091/62670559-eda73480-b993-11e9-9fa8-db4f2ec0d593.png)

**Nr.2**
![2019-08-07_01-05-52 166_top](https://user-images.githubusercontent.com/12501091/62670575-fd267d80-b993-11e9-99a8-02c733a502b5.png)

**Nr.3**
![2019-08-07_00-53-35 378_top](https://user-images.githubusercontent.com/12501091/62670589-0a436c80-b994-11e9-825f-74d7a0a3c7db.png)

**Nr.4**
![2019-08-07_01-24-47 724_top](https://user-images.githubusercontent.com/12501091/62670601-16c7c500-b994-11e9-8c3c-2c90d442e2a1.png)

**Nr.5**
![2019-08-07_01-29-12 650_top](https://user-images.githubusercontent.com/12501091/62670610-20512d00-b994-11e9-8c0b-665eb308d4ba.png)

**Nr.6**
![2019-08-07_01-58-19 819_top](https://user-images.githubusercontent.com/12501091/62670615-2a732b80-b994-11e9-8908-1179fdfd81a8.png)

**Nr.7**
![2019-08-08_00-23-03 173_bot](https://user-images.githubusercontent.com/12501091/62670646-424aaf80-b994-11e9-9a8e-33684b76b0de.png)

**Nr.8**
![2019-08-08_00-23-03 173_top](https://user-images.githubusercontent.com/12501091/62670678-52fb2580-b994-11e9-98c7-6b1ee231a83b.png)

**Nr.9**
![2019-08-08_00-27-05 814_top](https://user-images.githubusercontent.com/12501091/62670687-59899d00-b994-11e9-8363-da8eab0b696b.png)

### Additional Info
**Nr.1** I have screenshots of quite a number of the errors, but I'm not sure if there's any need to upload all of them (23 screenshots).

**Comment by lgnmcrules** [comment]
Fixed
