### ISSUE TITLE
Trade Goods menu required item name cutoffs

### ISSUE THREAD

**Issue by 1ted59** [teamrocketslime/RS3DS-Releases#14]
### Description
For multiple items in the Trade Goods menu, the names of the required items to produce the new item are cut off. This is due to the space for names being limited to 9 characters, even though there is more usable space visually.

Examples include:
"Desert Ro"[se] (for Medicinal Herb)
"Slimenia "[Log] (for Wood Arrow)
"Small Roc"[k] (for Iron Ball)
"Holy Wate"[r] (for Bamboo Barb)
"Thousandw"[eight] (for Iron Shield) (Notably, this item has ThousandWeight overflow the Key Item textbox for it when pressing X in the Trade Good menu)
"Slime Kni"[ght] (for Vulcan Gun)
"Devil's T"[ail] (for Devil's Scythe)
"Wood Arro"[w] (for Iron Arrow)
"Oaken Clu"[b] (for Irrataball)

More cutoff errors likely exist, but I have not unlocked everything on the menu yet.

### Location of bug
In the Trade Goods menu brought up by talking to Swotsy after proceeding some way throughout the adventure.

### Screenshot
![bamboo](https://user-images.githubusercontent.com/24933689/62677940-f68d0b80-b97d-11e9-8b6f-bffa7b6b18e7.png)
![ironball](https://user-images.githubusercontent.com/24933689/62677941-f725a200-b97d-11e9-87ef-655d5c6d6da0.png)
![ironshield](https://user-images.githubusercontent.com/24933689/62677943-f725a200-b97d-11e9-833a-567d3724fe19.png)
![medicinal](https://user-images.githubusercontent.com/24933689/62677944-f725a200-b97d-11e9-8a24-b42bc5d5e693.png)
![vulcangun](https://user-images.githubusercontent.com/24933689/62677945-f725a200-b97d-11e9-9d45-54b243bd3730.png)
![woodarrow](https://user-images.githubusercontent.com/24933689/62677947-f725a200-b97d-11e9-8f14-b46c1ab61841.png)
...etc

### Additional Info
Increasing the text length of the box would probably fix all but the 1kweight cutoff without issues.

**Comment by CakeLancelot** [comment]
I'll go ahead and increase the length of the textbox but it might lead to other issues such as text overflow onto the next line. Let me see if I could change the font size to alleviate this, perhaps.

**Comment by ultramario1998** [comment]
I've increased the size of the textbox and its parent panel; everything appears to be working fine. Closing this for now.
