### ISSUE TITLE
Error Reports - Second Pass

### ISSUE THREAD

**Issue by jakelui** [teamrocketslime/RS3DS-Releases#16]
- [x] End of credits reads:
...
SQUARE ENIX/KOICHI SUGIYAMA   ALL R
ights Reserved

- [x] Post credits, it reads: "Save this chat?" which should probably say something like "Save your progress?"

- [x] King says, "Take part in Naval Battles or fulfil requests..." (should be "fulfill")

- [x] King says, "You may learn new things from past aquaintances, too." (should be "acquaintances")

- [x] When you challenge Slival post-game, there is a dialogue box that appears when you leave Slival's Dragon Den and engage his ship. Hooly says something like "We're taking damage" or something that looks like it would be an in-battle dialogue box, but in the overworld.

Pictures of the two "automatic scrolling B" issue NPCs:

![IMG_3751](https://user-images.githubusercontent.com/8563100/62912910-dde67200-bd3e-11e9-8ab4-42572475650f.JPG)

![IMG_3686](https://user-images.githubusercontent.com/8563100/62912912-e048cc00-bd3e-11e9-81be-6da78c9655a9.JPG)

**Comment by lgnmcrules** [comment]
I can't reproduce the "b" issue

**Comment by lgnmcrules** [comment]
Do you have a picture of the Slival dialogue?

**Comment by jakelui** [comment]
i don't have a picture of the Slival post-game pre-battle dialogue, unfortunately. All I know is that Hooly said it immediately before the battle, after you head through the portal at the end of Slival's Hideout. The picture would look like your ship on the ocean, outside of Slival's base, facing Slival's ship, with the dialogue box.
