### ISSUE TITLE
Untranslated text, missing graphics, random words

### ISSUE THREAD

**Issue by zenseii** [teamrocketslime/RS3DS-Releases#18]
### Description
Nr.1 Untranslated name for "Mister-DL" when choosing "Agreement" while talking to him. Also typos: "received" and the text disappears while letters are still writing if you press a or b.
Nr.2 Missing graphic text and misalignment in bottom screen when dying in naval battle.
Nr.3 Strange appearance of "et" to the right after namebox for places for some requests in the request log. Top screen.

### Location of bug
Nr.1 Rightmost platywag from Cid.
Nr.3 So far found for Requests 46, 47,63, 74.

### Excerpt or Screenshot

- [x] **Nr.1**

![2019-08-25_04-16-12 950_top](https://user-images.githubusercontent.com/12501091/64503179-28b9c200-d2ca-11e9-86e9-993ef936d44c.png)

- [ ] **Nr.2**

![2019-09-07_00-02-12 411_bot](https://user-images.githubusercontent.com/12501091/64503172-20fa1d80-d2ca-11e9-969f-8fd1b7f3f33d.png)

- [x] **Nr.3**

![2019-09-05_06-06-37 144_bot](https://user-images.githubusercontent.com/12501091/64503198-425b0980-d2ca-11e9-86df-8700df139800.png)
![2019-09-05_06-06-37 144_top](https://user-images.githubusercontent.com/12501091/64503199-425b0980-d2ca-11e9-9ee9-318e6b0b4032.png)
![2019-09-05_06-07-13 199_bot](https://user-images.githubusercontent.com/12501091/64503200-42f3a000-d2ca-11e9-9805-dd57bd7deb96.png)
![2019-09-05_06-07-13 199_top](https://user-images.githubusercontent.com/12501091/64503201-42f3a000-d2ca-11e9-9278-78aae1096c66.png)
![2019-09-05_06-07-38 978_bot](https://user-images.githubusercontent.com/12501091/64503202-42f3a000-d2ca-11e9-85c1-014972389387.png)
![2019-09-05_06-07-38 978_top](https://user-images.githubusercontent.com/12501091/64503203-42f3a000-d2ca-11e9-91dc-ca8e53aad580.png)
![2019-09-05_06-06-06 781_bot](https://user-images.githubusercontent.com/12501091/64503204-42f3a000-d2ca-11e9-94a6-c0ce874dd6e3.png)
![2019-09-05_06-06-06 781_top](https://user-images.githubusercontent.com/12501091/64503205-438c3680-d2ca-11e9-8a86-3c95d907f15d.png)

**Comment by CakeLancelot** [comment]
Number 1: It seems the nameplate on this message is hardcoded. I will try to fix this in Beta 2, but keep in mind that the feature will always have untranslated text, since it is fetched from an online service. Not sure why it's cut off, though.
Number 2: Currently looking into a way to fix this
Number 3: it should read "etc" - this is fixed for Beta 2.

**Comment by CakeLancelot** [comment]
Nr. 2 is detailed in this issue: #23, everything else is fixed. Closing.
