### ISSUE TITLE
Place names and certain boxes

### ISSUE THREAD

**Issue by zenseii** [teamrocketslime/RS3DS-Releases#19]
### Description
Nr.1 Gun Valley City
Nr.2 Fossil Isle
Nr.3 West Slushia
Nr.4 Snow Country
Nr.5 Volcano Isle Harbor
Nr.6 Volcano Isle
Nr.7 Goddess Statue (and possibly more).
Nr.8 Walking Corpse (and possibly more).

### Location of bug
Nr.1-6 Bottom Screen Place names
Nr.7 Cid's Deck menu bottom screen item name in top right corner.
Nr.8 Cid's crew menu bottom screen bottom right corner it says "Walking Corps" and "e" is behind decription on next line.

### Screenshot

- [x] Nr.1
![2019-09-04_13-59-17 368_bot](https://user-images.githubusercontent.com/12501091/64504396-b2b85980-d2cf-11e9-83b0-bd0a5242b5e8.png)

- [x] Nr.2
![2019-08-22_18-52-53 675_bot](https://user-images.githubusercontent.com/12501091/64504404-b946d100-d2cf-11e9-906b-8156d2873bb6.png)

- [x] Nr.3
![2019-08-25_16-22-07 037_bot](https://user-images.githubusercontent.com/12501091/64504415-bfd54880-d2cf-11e9-895a-03c677f39aa5.png)

- [x] Nr.4
![2019-08-27_06-27-31 165_bot](https://user-images.githubusercontent.com/12501091/64504418-c663c000-d2cf-11e9-87a1-e3ed255800de.png)

- [x] Nr.5
![2019-09-05_05-39-10 746_bot](https://user-images.githubusercontent.com/12501091/64504440-e4c9bb80-d2cf-11e9-864b-5bb632937221.png)

- [x] Nr.6
![2019-09-05_05-40-52 896_bot](https://user-images.githubusercontent.com/12501091/64504438-e1cecb00-d2cf-11e9-978d-0818118b49ae.png)

- [x] Nr.7
![2019-08-27_05-51-46 324_bot](https://user-images.githubusercontent.com/12501091/64504445-eb583300-d2cf-11e9-8a71-a3b4d897f42e.png)

- [x] Nr.8
![2019-09-08_18-03-49 054_bot](https://user-images.githubusercontent.com/12501091/64504448-f01ce700-d2cf-11e9-89a6-7c771d3a95c5.png)

### Additional Info

**Comment by ultramario1998** [comment]
1. "Gun Valley City" changed to "Gun City". Thanks, @lgnmcrules
2. "Fossil Isle" textbox embiggened.
3. "West Slushia" and "West Slushia Harbor" shortened to "W. Slushia/Harbor".
4. "Snow Country" textbox embiggened.
5. "Volcano Isle Harbor" shortened to "Volcano Hbr."
6. "Volcano Isle" shortened to "Volcano", in keeping with the UI.
7. Not yet complete, unsure how to proceed with item name textboxes.
8. Embiggened ally monster nameplates (and fixed a few names while I'm at it)

**Comment by ultramario1998** [comment]
This has been resolved and will be fixed with the next release.
