### ISSUE TITLE
Additional patches do not work with translation.

### ISSUE THREAD

**Issue by ghost** [teamrocketslime/RS3DS-Releases#26]
### Description
Using other patches through layeredfs while using the translation at the same time causes the game to crash. The other patches do not crash the game is the translation is not present (both the fti folder and the code.ips are not present)

### Location of bug
The game crashes upon opening.

### Additional Info
Here is the error.
![error](https://user-images.githubusercontent.com/46581247/76372681-735cdb00-62fb-11ea-8e8e-bfba5997ff6f.jpg)

**Comment by CakeLancelot** [comment]
Currently the custom code.ips has its own layeredFS-like system built in, which conflicts with Luma, etc.

If you want to load in custom files for the game, the best way as of now is to place the files in the /fti/rocket_slime_3ds/data/ folder. It should correspond with the romFS file structure, though you will likely need to create some folders.

Removing the built-in support and using Luma's LayeredFS exclusively is something I've looked into, but not had much success with so far. So this will have to stay as-is for now.

**Comment by ghost** [comment]
I'm glad to know something like layeredfs will work, but through a different location. Thank you! I'll close the issue.
