### ISSUE TITLE
Soft lock after log collecting

### ISSUE THREAD

**Issue by meunierd** [teamrocketslime/RS3DS-Releases#3]
### Description
Following regaining control after collecting logs, I pressed start and the game stopped responding to input while music still played and animation still ran.

### Hardware
New 3DS XL

**Comment by CakeLancelot** [comment]
Are you able to reproduce this consistently? On my end I can't get the issue to occur: I hit start after getting out of the dialogue, but I'm able to then exit the pause menu and walk around as normal.

**Comment by meunierd** [comment]
I can't seem to reproduce. I'll close and reopen if I can trigger it again
