### ISSUE TITLE
Error Reports - First Pass

### ISSUE THREAD

**Issue by jakelui** [teamrocketslime/RS3DS-Releases#4]
**Dialogue Overflow:**

- [x] Boing defeated the chef's ship wit
h
a cake on it!

- [x] Boing handed over 1 Meteorite Bra
cel to the 
priest!

- [x] Boy Admirer
Hey, have you traded yet? If so, ha
ve
you done it more than 5 times?

- [x] Bring me 20 Cruelcumber! I'll join y
our
crew if you do!

- [x] Collect 20 Evil Imp
. If ya get 'em for me,
I'll join ya crew!

- [x] Girl
I want ya to fight a ship that look
s
like a zombie, will ya?

There's others that I missed or don't remember anymore. It usually happens when accepting or completing an NPC quest.

**NPC Name Changes:**
- [x] Purple Rock Slime in the Desert goes from "Old man" to "Fattie"
- [x] Green Slime at the front in Slimenia goes from "Towngirl" to "Young kid"
- [x] Grandpa Slime in Slimenia goes from "Granpappy" to "Gramps"

**Typos:**

- [x] General note: very often it reads "Rainbow orbs" instead of "Rainbow Orbs"
- [x] Before one of the ship battles: "[...] en guarde!" should be "en garde!"
- [x] Baron Barbe (is that supposed to be the name?) asks for 3 Shells "si'l vous plait" (should be "s'il vous plait", apostrophe comes after the s)
- [x] Gem Slime in Slimenia named "Prof" says at the beginning of the game, "I'mma professor! Imma alwaysa doing research." (inconsistency with I'mma and Imma)
- [x] When the Platywags steal the orbs, the boss is listed as "Don Clawleon" (should be Don Clawleone)
- [x] "Boy" slime in Slimenia says, "That cool ship I saw? [...] the Platywags's ship?" (should be Platywags' ship, no s after apostrophe)
- [x] Mrs. Hooly says, "So these pirates were the Platywags" (no punctuation)
- [x] The first time the Painting is defeated, it says, "[...] rendevous again" (should be "rendezvous")
- [x] "It seems like the orb is at Funadel Mansion!" is spoken by "Hooley" (should be "Hooly")
- [x] during one of the Heady/Taily dialogues, Taily says "treking" (should be "trekking")
- [x] When you first challenge Slival at the ship graveyard, Slival says, "Now! if yarr ready [...]" ("if" should be capitalized to "If". Interestingly, if you decline and then ask Slival again, he gets the capitalization right the second time)
- [x] Dr. Cid says, "Woah, you really vere a prince..?" ("Woah" should be "Whoa" and ellipsis should be three dots "...?")
- [x] When returning the six orbs, King says, "[...] Only one orb remainins." (should be either "remains." or "remaining.")
- [x] In Zipunk, Platurai says, "[...] You got beat by such chilrden?" (should be "children?")
- [x] Slival says, "Yarr owe me another match for that dissapointing fight!" (should be "disappointing")
- [x] in town, Restless Armor's name gets cut off ("Restless Armo")
- [x] as well as "Power Hamme"
- [x] during Taily's float jump tutorial, he says "manuver around" instead of "maneuver around" (though it is correctly spelled the next time it appears)
- [x] "Sheikh" in Slushia says "[...] you've come along way" instead of "a long way"
- [x] the gem slime in Slushia is named "Archeologist" instead of "Archaeologist"
- [x] when Slival introduces himself: "My NAME is Silval. Don't you forget it."
- [x] after that, Hooly says "[...] pinpoint the orbs power" (should be "orbs' power")
- [x] rematch with the sphinx: it says "Thanks to the life the orb, [...]" idk what the sentence is supposed to be
- [x] after the Goonin ninjas do the recon: "We rescued a townsman who was being assualted [...]" (assaulted)

**Other:**

- [x] slime on the green blanket in the desert town has no name label
- [x] Baron Tubby should be Baron Blubba
- [x] one issue that came up a few times is that sometimes, in a text box when you hit B to skip the scrolling and see the full text, it automatically moves to the next text box. It's like a B and an A at the same time. There's a slime with a crown in the upper left of Slimenia by the bridge, and a Dark Slime named "Hiking lover" in Shiveral who do this.
- [x] in the menu screen, the description for Battle Axe is still in kana, strangely

**Comment by CakeLancelot** [comment]
Thanks for the detailed report! We should be able to fix these for the next release, I'll close this once everything listed is fixed internally.

**Comment by zenseii** [comment]
I believe I captured the typo on "trekin'".

> ![IMG_20190806_015830](https://user-images.githubusercontent.com/12501091/62663755-24bc1c80-b979-11e9-8cfd-3d3630168825.jpg)

**Comment by CakeLancelot** [comment]
I've edited the main post to use check boxes, which should make it easier to see which ones are fixed.

**Comment by lgnmcrules** [comment]
What does the slime say on the green towel for the name plate?

**Comment by jakelui** [comment]
There is no name plate.

![IMG_2522](https://user-images.githubusercontent.com/8563100/62839199-9d520000-bc3b-11e9-827a-20a245c1564e.JPG)

**Comment by lgnmcrules** [comment]
Could you show me the instances where hitting 'B' causes issues?

**Comment by jakelui** [comment]
![IMG_3751](https://user-images.githubusercontent.com/8563100/62912086-7e3a9780-bd3b-11e9-9658-0ed1d40bec74.JPG)
![IMG_3686](https://user-images.githubusercontent.com/8563100/62912088-809cf180-bd3b-11e9-8336-6ba6a0cbda76.JPG)

**Comment by jakelui** [comment]
In addition:

- [ ] End of credits reads:
...
SQUARE ENIX/KOICHI SUGIYAMA   ALL R
ights Reserved

- [ ] Post credits, it reads: "Save this chat?" which should probably say something like "Save your progress?"

- [ ] King says, "Take part in Naval Battles or fulfil requests..." (should be "fulfill")

- [ ] King says, "You may learn new things from past aquaintances, too." (should be "acquaintances")
