### ISSUE TITLE
Typo on Sphinx Refight

### ISSUE THREAD

**Issue by 1ted59** [teamrocketslime/RS3DS-Releases#6]
### Description
On refight of the sphinx boss, immediately before fighting it again it says:
"Grrr... **Thanks to the life the orb**, I will be called forth once more"
The grammar of the first part of the sentence is incorrect.

### Location of bug
First boss in the desert area, on immediate refight.

### Excerpt or Screenshot
![typo](https://user-images.githubusercontent.com/24933689/62438369-11a91280-b715-11e9-83c7-75bdc9680726.png)

### Additional Info
Typo does not appear on first fight due to different text.

**Comment by CakeLancelot** [comment]
Thanks, should be fixed in the next beta!
