### ISSUE TITLE
Request 3 slime's name: "Juenesse"

### ISSUE THREAD

**Issue by joshleaves** [teamrocketslime/RS3DS-Releases#7]
### Description
The slime for request 3 is called "Juenesse". Since he's (obviously) from France (and so are the slimes of Req.4 and 5, "Angelique" and "Baron Barbe"), therefore, the name should be "Jeunesse" ("youth").

### Location of bug
I've only noticed it on the "Quests" menu (Start, then R). However, not sure if it's only on this screen, or whether it also happens in the slime's in-game dialogue.

### Excerpt or Screenshot
![image](https://user-images.githubusercontent.com/1074760/62467220-7f941f00-b793-11e9-82a7-9d384f98a6ec.png)

**Comment by CakeLancelot** [comment]
I fixed it in the quest dialogue, but I will have to look into in-game dialogues.

**Comment by lgnmcrules** [comment]
Should be fixed
