### ISSUE TITLE
"Bu" part shop, Goal texts

### ISSUE THREAD

**Issue by zenseii** [teamrocketslime/RS3DS-Releases#9]
### Description

Nr. 1 
In the description in down right corner of bottom screen it says "Bu" instead of Buy

Nr.2
Some Goal texts on the bottom screen get cut off. 
Ex.1 "Return to the Snow Country o". 
Ex2 "Found the map in the graveya".

### Location of bug
Nr.1 Every one of the German Jans ship part shops.
Nr.2 Bottom screen.

### Screenshot

- [x] Nr.1

![2019-08-07_01-12-04 203_bot](https://user-images.githubusercontent.com/12501091/62660549-9b9fe800-b96e-11e9-85af-79354c13d8e1.png)

Nr.2

- [x] Ex.1

![2019-08-30_22-51-58 999_bot](https://user-images.githubusercontent.com/12501091/64500269-c7d7bd00-d2bc-11e9-8976-26b0b16ee858.png)

- [x] Ex.2

![2019-08-31_00-15-09 562_bot](https://user-images.githubusercontent.com/12501091/64503567-e5f8e980-d2cb-11e9-91ad-39c1a5d321ad.png)

**Comment by CakeLancelot** [comment]
Noted, thanks for the report!

**Comment by zenseii** [comment]
Thank YOU for the translation. Btw do you prefer my issues in separate issues or should I just make one issue containing all the ones I have so far? Also I'm planning on putting the similar issues I have found in the same issue. For example, I have maybe 14 grammar errors and it seems unnecessary to make an issue for all of them instead of just putting them into the same issue regarding grammatical errors.

Also I found using Luma's screenshot feature to be very handy, so maybe we should tell others to do it. It literally takes 3 seconds whenever you spot something you want to report.

**Comment by CakeLancelot** [comment]
> Btw do you prefer my issues in separate issues or should I just make one issue containing all the ones I have so far?

Grouping would be preferred if the issues are similar enough - as a general rule more than 2 or 3 similar errors can be put together into one report.

> Also I found using Luma's screenshot feature to be very handy, so maybe we should tell others to do it.

A tutorial for Luma screenshots should also help, since most of the templates *do* ask to specify screenshots after all. I'll look into adding it in the future.

**Comment by ultramario1998** [comment]
Fixed. Extended length of button textbox.

**Comment by zenseii** [comment]
Added issue.

**Comment by ultramario1998** [comment]
Fixed. Changed text in textbox to fit. Thanks so much!
